### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by trishin-pinedev** [anaseqal/nova-import#1]
Good day, thank you so much for the work, it's nice to have action button which not refers to specific item of resource!

Do you plan to add action name customization? When I'm trying apply custom name with
`public $name`
within Action class, then button will just disappear, and thus in javascript need to be implemented some dirty things. The same goes for the title.

Excuse me for bad English :)

**Comment by anaseqal** [comment]
Good day to you too.

i don't fully understand your suggestion but for translate import button, i used
`{{ __('Import') }} {{ __(resourceInformation.label) }}`

**Comment by anaseqal** [comment]
> Good day, thank you so much for the work, it's nice to have action button which not refers to specific item of resource!
> 
> Do you plan to add action name customization? When I'm trying apply custom name with
> `public $name`
> within Action class, then button will just disappear, and thus in javascript need to be implemented some dirty things. The same goes for the title.
> 
> Excuse me for bad English :)

Try this :

```

        /**
	 * Get the displayable name of the action.
	 *
	 * @return string
	 */
	public function name() {
		return __('Import Users');
	}

    /**
     * @return string
     */
    public function uriKey() :string
    {
        return 'import-users';
    }
```
