### ISSUE TITLE
Button doesn't appear in relationship

### ISSUE THREAD

**Issue by LorenzoSapora** [anaseqal/nova-import#10]
Nova: 2.9.4
Laravel: 5.8.*
Nova-import: 0.0.2

-------------------------

Am I missing something here?

Problem: Action not appearing on `HasMany` relationship.

I have an 'import keys' action on my key resource. Works fine.

The keys have a label group. On the label resource, I have a `HasMany` that displays attached keys correctly, but doesn't give me the action to import keys to said label. 

There's nothing in the `Action` class that would lead me to believe I'm missing a function.

**Comment by anaseqal** [comment]
Hello,

Yes this is limitation by nova where ustom-index-toolbar doesn't appear in relations header:

```
<custom-index-toolbar
     v-if="!viaResource"  <--- this
     :resource-name="resourceName"
/>
```
