### ISSUE TITLE
Authorization issue causes an error to occur when you don't have any resource saved in the database

### ISSUE THREAD

**Issue by Otienoh** [anaseqal/nova-import#13]
### Related Issue 

[https://github.com/laravel/nova-issues/issues/542](https://github.com/laravel/nova-issues/issues/542)

Currently experiencing this weird behavior  as described by @vincenzoraco

### Issue

I had the same problem, I was using this package https://novapackages.com/packages/anaseqal/nova-import which helps me to import resources. The error occurs when you don't have any resource saved on the database.

It seems that Nova is checking if there are any saved resourced, is it the right behavior? It does make sense to me, but it stops us to import the initial data, if any.

### Proposed Solution

So for those who are facing this issue, create a dummy record on the table, then import, and then delete the dummy row

Thanks

**Comment by shazibrazzaq** [comment]
i am having the same issue, can we have it fixed in the package??

**Comment by anaseqal** [comment]
Hello,

Are you sure you are using the custom action:
use Anaseqal\NovaImport\Actions\Action;

because it shouldn't have (Sorry! You are not authorized to perform this action.) danger message.

**Comment by Otienoh** [comment]
@anaseqal You are right! I was importing the laravel action.

Fixed by importing `use Anaseqal\NovaImport\Actions\Action;`

**Comment by curtisblackwell** [comment]
[Here's the solution I find more robust than others I've seen.](https://github.com/laravel/nova-issues/issues/542#issuecomment-870105531)
