### ISSUE TITLE
queue issue

### ISSUE THREAD

**Issue by pyramid-ali** [anaseqal/nova-import#16]
Hi,
in your DispatchAction class line 58
```php
protected static function queueForModels(ActionRequest $request, Action $action, $method, Collection $models)
```
you typehint $models with Collection, but you use
```php
use Illuminate\Support\Collection;
```
instead of 
```php
use Illuminate\Database\Eloquent\Collection;
```
this cause this issue:
`
Argument 4 passed to Anaseqal\NovaImport\Actions\CallQueuedAction::__construct() must be an instance of Illuminate\Database\Eloquent\Collection, instance of Illuminate\Support\Collection given, called in ...
`
thank you for your great job

**Comment by pyramid-ali** [comment]
this error will occur when you use ShouldQueue interface on your action class

**Comment by 0xZeus** [comment]
Hello @pyramid-ali 

Consider using Laravel Excel Queues instead of Nova Action Queues:

https://docs.laravel-excel.com/3.1/imports/queued.html

**Comment by anaseqal** [comment]
Hello @pyramid-ali

Consider using Laravel Excel Queues instead of Nova Action Queues:

https://docs.laravel-excel.com/3.1/imports/queued.html
