### ISSUE TITLE
Button is always displaying in english but my app is in French 

### ISSUE THREAD

**Issue by xoco70** [anaseqal/nova-import#18]
Hi, 

Plugin seems to be working great, but my app is in French, and Button sticks with the text : "Import Users". At side, the create user buttons says: "Créer Utilisateur", because I named my resource "Utilisateur". 

Is there a way to change this ???

I'm using Nova 2.x with Laravel 6

**Comment by curder** [comment]
Hi Xoco70, You can change your `resources/lang/vendor/nova/{locale}.json` file, add your custom configuration. 

for example: `"Import qa-users": "批量导入"`, and the `qa-users` is your resource name.

**Comment by xoco70** [comment]
Thanks ! It worked like a charm !
