### ISSUE TITLE
Missing Traits

### ISSUE THREAD

**Issue by joaodman** [anaseqal/nova-import#2]
When trying to use the package I'm getting:
`Trait 'Laravel\\Nova\\Metable' not found at /var/www/vendor/anaseqal/nova-import/src/Actions/Action.php:19`
And `Trait 'Laravel\\Nova\\AuthorizedToSee' not found at /var/www/vendor/anaseqal/nova-import/src/Actions/Action.php:20`
Did you forget to include this traits, or am I missing something?

**Comment by anaseqal** [comment]
Which nova version you are using, this is only tested on nova 2.

**Comment by joaodman** [comment]
I'm using Nova 1.0 for this project, will look into upgrading it. That is most likely the cause. Thank you.
