### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by francoisauclair911** [anaseqal/nova-import#4]
Hi, Awesome package by the way,

I was wondering if there was a way to pass the Resource type and ID to the action so I can avoid having the ID and type within the CSV itself and just deduct it from where the Request is coming from (which resource page)

**Comment by anaseqal** [comment]
> Hi, Awesome package by the way,
> 
> I was wondering if there was a way to pass the Resource type and ID to the action so I can avoid having the ID and type within the CSV itself and just deduct it from where the Request is coming from (which resource page)

I am not sure if you can as it's general Nova question, but if you want to pass some custom fields to the import from action you can do like so:
```
/**
     * Perform the action.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @return mixed
     */
    public function handle(ActionFields $fields)
    {
        Excel::import(new UsersImport($fields), $fields->file);
        return Action::message( __('Users imported successfully!'));
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            File::make('file')->rules('required'),
            Text::make('custom'),
        ];
    }
```
And in your import file :

```
use Laravel\Nova\Fields\ActionFields;
...

    private $fields;

    public function __construct(ActionFields $fields) {
        $this->fields = $fields;
    }


```
