### ISSUE TITLE
Not showing button and can't get onlyOnIndex working

### ISSUE THREAD

**Issue by patricktsg** [anaseqal/nova-import#5]
I have followed the setup docs but I can't seem to get the Import button showing on the index page, when I set  public $onlyOnIndex = false; I see the action only on the detail page.

**Comment by patricktsg** [comment]
**Solved:** I needed to pluralise the actions names, I overlooked the importance of that in the docs.

**Comment by ahmadhidayatullah** [comment]
Hi, i had renamed to pluralise action names but the button still not showing.

the import file must pluralise name ?

**Comment by ahmadhidayatullah** [comment]
**Solved** : the uriKey in action file must reference name of the action.

**Comment by daugaard47** [comment]
>  the uriKey in action file must reference name of the action.

I cannot see the import button on an empty table. I have to create a record then check the box to see the action dropdown.

@rangerbiru Can you show what you did to get this to work?
In my action I have the following:

```
class ImportSalesForceRecords extends Action
{
public $onlyOnIndex = true;

    public function name() {
        return __('Import Sales Force Records');
    }

    public function uriKey() :string
    {
        return 'import-sales-force-records';
    }
}

//IN Nova Resource
    public function actions(Request $request)
    {
        return [new ImportSalesForceRecords];
    }
```
