### ISSUE TITLE
Nova 2.5.0 - Button text is not showing

### ISSUE THREAD

**Issue by HaykDrnoyan** [anaseqal/nova-import#7]
Hi!

After upgrading to Nova 2.5.0 the import button text disappeared https://prnt.sc/pjwny0 https://prnt.sc/pjwo4d

**Comment by ns139426** [comment]
There are new text properties on the Nova Action class that are returned as part of the JSON output, the Vue template for the modal requires these to display correctly.

`public function jsonSerialize()
    {
        return array_merge([
            'cancelButtonText' => __($this->cancelButtonText),
            'component' => $this->component(),
            'confirmButtonText' => __($this->confirmButtonText),
            'confirmText' => __($this->confirmText),
            'destructive' => $this instanceof DestructiveAction,
            'name' => $this->name(),
            'uriKey' => $this->uriKey(),
            'fields' => collect($this->fields())->each->resolve(new class {
            })->all(),
            'availableForEntireResource' => $this->availableForEntireResource,
            'showOnDetail' => $this->shownOnDetail(),
            'showOnIndex' => $this->shownOnIndex(),
            'showOnTableRow' => $this->shownOnTableRow(),
            'withoutConfirmation' => $this->withoutConfirmation,
        ], $this->meta());
    }`

You can easily add these properties and associated methods to the Action class within the package and they'll display again.

**Comment by HaykDrnoyan** [comment]
@ns139426 Great. Thanks!

**Comment by ns139426** [comment]
It might be worth leaving this issue open as the problem still exists and needs to be fixed.

**Comment by HaykDrnoyan** [comment]
Ok, reopened.

**Comment by anaseqal** [comment]
Thanks for reporting, Fixed !
