### ISSUE TITLE
Drop dependency to maatwebsite/excel ?

### ISSUE THREAD

**Issue by slackernrrd** [anaseqal/nova-import#8]
Thanks for a great package!

I am using this package to import data from JSON-files instead of Excel, which works great. From my point of view, the dependency to `maatwebsite/excel` isn't really necessary. It can be required in the project when needed. `maatwebsite/excel` requires `phpoffice/phpspreadsheet` which in turn requires the PHP zip extension, which in my case is totally unnecessary.

Could the dependency be dropped?

**Comment by anaseqal** [comment]
Hello @slackernrrd 
I will do that in new nova package soon.
Thank you for your note.
